baseURL = 'https://vishymakthal.com'
languageCode = 'en-us'
title = 'Vishy Makthal'
theme = "cactus"
googleAnalytics = 'G-WDVD19M799'

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Gallery"
url = "/gallery"
weight = 2

[[menu.main]]
name = "Stand Up"
url = "/standup"
weight = 4

[params]

    colortheme = "white"

    description = "**Vishy Makthal** is a comedian and writer based in  **New York City**.  He was raised in both **Hyderabad, India** and **Raleigh, NC**. As a South Indian from the South, Vishy's clashing identities have left him with a penchant for **sharp observational humor** and a liking for Bojangles with Dal Chawal. He's been featured on shows stateside (**Goodnights Comedy Club**, **Broadway Comedy Club**, **Greenwich Village Comedy Club**) and abroad, having performed in India and Europe. Vishy has shared the stage with many talented performers along the way, including **Seth Meyers** and **Ralph Barbosa**."

    [[params.social]]
        name = "instagram"
        link = "https://www.instagram.com/veeshm8"
    [[params.social]]
        name = "twitter"
        link = "https://www.twitter.com/veeshm8"
    [[params.social]]
        name = "tiktok"
        link = "https://www.tiktok.com/@fanofwholefoods"
